export const contentInput = [
  "May sikreto akong hindi alam ng kahit sino...",
  1500,
  "Dito ko lang kayang sabihin ang totoo...",
  1500,
  "Anonymous lang ako, pero totoo ang nararamdaman ko...",
  1500,
  "May kasalanan akong hanggang ngayon dala-dala ko...",
  1500,

  "Crush kita pero hanggang dito na lang muna...",
  1500,
  "Hindi mo alam, pero ikaw ang dahilan ng ngiti ko...",
  1500,
  "May gusto ako sa’yo, pero hanggang isip lang...",
  1500,
  "Araw-araw kitang naiisip, kahit bawal...",
  1500,
  "Kung alam mo lang kung gaano kita gusto...",
  1500,

  "Hindi ko na alam kung gutom ba ako o malungkot...",
  1500,
  "Nag-open ako ng app na ’to para mag-confess, hindi para umiyak...",
  1500,
  "Ako lang ba ang napapagod kahit wala namang ginagawa?",
  1500,
  "Confession: mas mahal ko ang tulog kaysa sa lahat...",
  1500,
  "May sasabihin sana ako, pero nakalimutan ko na...",
  1500,

  "Nakakapagod maging mabait palagi...",
  1500,
  "Hindi lahat ng ngiti ay okay ang ibig sabihin...",
  1500,
  "Galit ako, pero hindi ko alam kung kanino...",
  1500,
  "Pwede bang mapagod na lang muna?",
  1500,
  "Hindi fair, pero wala naman akong choice...",
  1500,

  "Ako lang ba ang laging nag-o-overthink?",
  1500,
  "Minsan iniisip ko kung may meaning pa ba lahat...",
  1500,
  "Parang ang ingay ng isip ko kahit tahimik ang paligid...",
  1500,
  "Hindi ko alam kung drama lang ba ’to o pagod...",
  1500,
  "Gusto ko lang huminga nang walang iniisip...",
  1500,

  "Pagod na ako, pero tuloy pa rin...",
  1500,
  "Hindi ko kailangan ng solusyon, gusto ko lang mailabas...",
  1500,
  "May bigat sa dibdib na hindi ko maipaliwanag...",
  1500,
  "Sana may makaintindi kahit hindi nila ako kilala...",
  1500,
  "Salamat kung may makakabasa man nito...",
  1500,

  "Baka bukas, mas okay na ako...",
  1500,
  "Unti-unti, sinusubukan ko ulit...",
  1500,
  "Hindi man ngayon, pero balang araw...",
  1500,
  "Ito muna ang pahinga ko...",
  1500,
  "Simula pa lang ’to ng pagiging totoo ko...",
  1500,
];
