export const contentInput = [
  // Sikreto / Pagbubukas
  "May tinatago talaga akong sikreto, bes...",
  1500,
  "Dito lang ako nagiging totoo, promise...",
  1500,
  "Anonymous nga lang ako pero legit ’to, hindi char...",
  1500,
  "May guilt akong dala-dala hanggang ngayon, grabe...",
  1500,
  "Sana dito lang ’to mag-stay, wag mo na palabasin hehe...",
  1500,
  "First time ko ’to sasabihin, kinakabahan ako ngayon...",
  1500,
  "Kung alam mo lang ang totoong nangyayari sa utak ko rn...",
  1500,
  "Malapit na ’tong maging deep, heads up...",
  1500,

  // Crush / Pag-ibig
  "Alam mo ba, cursh na cursh kita talaga...",
  1500,
  "Crush kita pero chill lang muna ako, wag mag-alala...",
  1500,
  "Hindi mo alam pero ikaw yung bet ko, sorry not sorry...",
  1500,
  "May gusto ako sa’yo pero sa isip pa lang, char...",
  1500,
  "Araw-araw kang nasa isip ko, sobra na ’to ah...",
  1500,
  "Kung alam mo lang gaano kita ka-bet, grabe...",
  1500,
  "Ikaw yung laging pumapasok sa isip ko nang walang paalam...",
  1500,
  "Gustong-gusto na sana kitang sabihan pero takot pa rin, hays...",
  1500,
  "Simpleng chikahan lang natin, na-good vibes na agad ako...",
  1500,
  "Alam mo bang ang importante mo, kahit di mo alam?",
  1500,
  "Ilang beses ko nang na-rehearse ’to sa harap ng salamin, LOL...",
  1500,
  "Baka isang araw, malakas na ako sabihin sa’yo mismo...",
  1500,
  "Tingin lang muna ako, wag mo akong bilhin ha...",
  1500,
  "Gusto talaga kitang makilala nang mas malapitan...",
  1500,
  "Naiisip kita kahit busy na busy, ang tibay mo talaga sa isip ko...",
  1500,
  "Sana ma-notice mo rin ako paminsan-minsan, please lang...",
  1500,
  "Ayoko munang umasa kasi baka masaktan ako, pero gigil na ’ko...",
  1500,
  "Sa dami ng tao, ikaw pa rin talaga ang nakikita ko, weird diba?",
  1500,
  "Cursh na cursh, pero coward mode activated pagdating sa umamin...",
  1500,
  "May tahimik na umiibig sa’yo, ikaw lang ang di nakakaalam...",
  1500,

  // Random / Everyday moods
  "Di ko alam kung gutom ba ’ko o sad lang, classic...",
  1500,
  "Nag-open ako ng app na ’to para mag-confess, hindi para umiyak ha...",
  1500,
  "Ako lang ba ang pagod na pagod kahit wala namang ginawa?",
  1500,
  "Confession: mas mahal ko ang tulog kaysa buong mundo, char naman...",
  1500,
  "May sasabihin sana ’ko pero nakalimutan ko na, ganern...",
  1500,
  "Bakit ang bilis ng oras pag ayaw mo pa siyang tumakbo, ha?",
  1500,
  "Minsan gusto ko na lang mag-disappear ng isang araw lang...",
  1500,
  "Parang kahapon pa lang pero pagod na agad ako today, sana all energy...",
  1500,
  "Sana may pause button para sa buhay, please lang universe...",
  1500,
  "Gusto ko lang ng tahimik na gabi ngayon, no drama please...",
  1500,

  // Nakakapagod / Pagod
  "Nakakapagod maging mabait lagi, pero ayun okay lang...",
  1500,
  "Hindi lahat ng ngiti, okay ang ibig sabihin, alam mo naman ’yan...",
  1500,
  "Bad trip ako pero di ko alam kung kanino i-direct, char...",
  1500,
  "Pwede bang mapagod na lang muna, bes? Sobra na kasi...",
  1500,
  "Hindi fair pero wala naman akong choice diba, ganito na lang...",
  1500,
  "Pagod na ’kong magpanggap na okay lang lagi, tanggap na...",
  1500,
  "Sawa na ’kong maging maunawain lagi lagi, minsan lang naman...",
  1500,
  "Ilang beses ko nang sinabing okay lang ’ko, pero hindi naman, LOL sad...",
  1500,
  "Minsan gusto ko na lang sumuko pero di ko rin kaya, ang labo...",
  1500,
  "Di ko na alam kung gaano pa ’ko katatag, pero sige tuloy pa rin...",
  1500,

  // Overthinking / Isip
  "Ako lang ba ang laging nag-o-overthink? Sana hindi...",
  1500,
  "Minsan iniisip ko kung may point pa ba lahat, deep tonight...",
  1500,
  "Ang ingay ng utak ko kahit tahimik ang paligid, weird flex...",
  1500,
  "Di ko alam kung drama lang ba ’to o legit pagod, char...",
  1500,
  "Gusto ko lang huminga nang walang iniisip, sana one day...",
  1500,
  "Bakit ba ang hirap patahimikin ang isip pag gabi na? Every time...",
  1500,
  "Sana huminto na ang isip ko sa pag-analyze ng lahat, please...",
  1500,
  "Parang laging may kulang kahit ayos naman lahat, kabog...",
  1500,
  "Bakit lahat ng bagay, iniisip ko nang sobra? Tired na ’ko sa sarili ko...",
  1500,
  "Gusto ko lang tumigil kahit sandali lang, kahit sa isip lang...",
  1500,

  // Emosyonal / Pahayag
  "Pagod na ’ko pero tuloy pa rin, ganyan talaga siguro...",
  1500,
  "Ayoko ng solusyon, gusto ko lang mailabas, plz lang pakinggan...",
  1500,
  "May bigat sa dibdib na di ko maexplain, hays buhay...",
  1500,
  "Sana may makaintindi kahit di nila ’ko kilala, that’s all I need...",
  1500,
  "Salamat kung meron mang nakabasa nito, seryoso ’to...",
  1500,
  "Minsan ang lakas ko raw pero gusto ko lang din maiyak paminsan...",
  1500,
  "Hindi porket okay ang mukha ko, okay na rin talaga ako, sabi ko lang...",
  1500,
  "Gusto ko lang malaman ng isang tao ang totoong feelings ko, sobrang...",
  1500,
  "Marami akong tinatago kahit sa taong pinaka close sa ’kin, awit...",
  1500,
  "Sana hindi masamang tao ang makakabasa nito, pero if ikaw, hi...",
  1500,

  // Pag-asa / Paglago
  "Baka bukas, mas okay na ’ko, sana totoo...",
  1500,
  "Unti-unti lang, sinusubukan ko ulit, one day at a time...",
  1500,
  "Hindi man ngayon pero balang araw, keri lang ’to...",
  1500,
  "Ito muna ang pahinga ko, wag mo akong pag-alalahanin...",
  1500,
  "Simula pa lang ’to ng pagiging totoo ko, sana proud ka ’king mamaya...",
  1500,
  "Kahit paunti-unti, tuloy pa rin ’ko, promise ’yan...",
  1500,
  "May pag-asa pa naman kahit mabagal, sabi nila slow lang daw...",
  1500,
  "Di ’ko sumusuko, nagpapahinga lang muna, ibang usapan ’yon...",
  1500,
  "Malapit na siguro ang magandang araw ko, manifesting rn...",
  1500,
  "Sana bukas, mas magaan na ang pakiramdam ko, please please...",
  1500,

  // Pasasalamat / Simpleng saya
  "Salamat sa mga taong tahimik lang pero laging andiyan, love you guys...",
  1500,
  "Konting bagay lang minsan, sapat na para masaya ’ko, sana all appreciate small wins...",
  1500,
  "Masaya ’ko kahit sa maliliit na bagay lang, that’s enough na...",
  1500,
  "Salamat sa araw na ’to kahit ordinaryo lang, sobra pa rin thankful...",
  1500,
  "Grateful ’ko kahit simple lang buhay ko ngayon, no cap...",
  1500,
  "Masaya akong buhay pa ’ko para sa araw na ’to, cheers to that...",
  1500,
  "May mga bagay pala akong dapat ipagpasalamat, natutunan ko lang ngayon...",
  1500,
  "Salamat sa taong nagbigay ng konting saya sa araw ko, alam mo na kung sino ka...",
  1500,

  // Tao / Relasyon
  "Minsan iniisip ko kung may nagmamahal pa ba sa ’kin nang totoo, deep...",
  1500,
  "Gustong-gusto ko sanang malaman ang totoong saloobin niya, char pero seryoso...",
  1500,
  "Mahirap magtiwala ulit pagkatapos ma-hurt, alam mo ’yan diba...",
  1500,
  "Sana may taong maghintay sa ’kin nang di napapagod, please lang...",
  1500,
  "Minsan mas gusto ko nang mag-isa kaysa masaktan pa ng iba, sorry not sorry...",
  1500,
  "Sana yung mahal ko, alam din niya gaano ko siya ka-bet, chismis lang ’to sarili ko...",
  1500,
  "Natatakot akong umasa ulit pagkatapos masaktan, trust issues fr...",
  1500,
  "Kahit ilang beses akong nasaktan, gusto ko pa ring magmahal, weird pero true...",
  1500,

  // Pagpapatibay sa sarili / Motivation
  "Kaya ko ’to, kahit mabagal lang takbo ko, chill lang...",
  1500,
  "Hindi ’ko mag-isa sa laban na ’to, sana all support system...",
  1500,
  "Isang hakbang lang muna, kahit maliit, baby steps na lang...",
  1500,
  "Proud ako sa sarili ko kahit walang kasabay sa journey, self-love moment...",
  1500,
  "Sana matutunan ko na ring maging mabait sa sarili ko, one day totoo ’to...",
  1500,
  "Deserve ko rin ng kabutihan, kahit nakakalimutan ko minsan, PSA to self...",
  1500,
  "Kaya ko ’to, dahan-dahan lang, walang rush...",
  1500,
  "Hindi biro ’tong nararanasan ko pero patuloy pa rin ’ko, sana matapos na rin ’to...",
  1500,
];
