export const playfulTitles: string[] = [
  "Shh… you’re sneaking an anonymous message for {username} 😎",
  "Dropping some mystery mail for {username} 👀",
  "Sliding into the inbox for {username}… anonymously 🤫",
  "Time to mess with {username}… secretly 😏",
  "Psst… secret message incoming for {username} 🕵️",
  "Whispers in the digital wind for {username} 🌬️",
  "Your secret is safe with us for {username} 🤐",
  "Anonymous vibes only for {username} ✨",
  "A mysterious message appears for {username}… 👻",
  "Ssshh… ninja messaging mode for {username} 🥷",
  "Oops… someone’s sneaky for {username} 😼",
  "Confession time! But shh for {username} 🤭",
  "Ghost message on the way for {username} 👻",
  "Sliding through quietly for {username}… 🛷",
  "Mysterious whispers incoming for {username} 🌀",
  "Hey, it’s a secret note for {username}! 📜",
  "Top secret: your inbox for {username} 🕶️",
  "Message cloaked in mystery for {username} 🕵️‍♂️",
  "Shhh… digital ninja at work for {username} 🥷",
  "Your anonymous delivery for {username} 🚀",
  "Mystery vibes heading to {username} 🕶️",
  "Sneaky surprise for {username} 😏",
  "Quietly sliding this to {username} 🤫",
  "Top-secret whispers for {username} 🕵️",
  "Shhh… confidential message for {username} 🤐",
  "A mysterious note just for {username} 👀",
  "You’ve got an anonymous whisper for {username} 🌬️",
  "Sliding stealthily into {username}’s inbox 🥷",
  "Message in a bottle for {username} 🍼",
  "Secretly plotting a note for {username} 😼",
  "Mysterious vibes only for {username} ✨",
  "Ghostly message incoming for {username} 👻",
  "Oops… something anonymous for {username} 😏",
  "Psst… {username} is about to get a secret 🕵️",
  "Quiet as a ninja for {username} 🥷",
  "Anonymous vibes on the way for {username} 🚀",
  "Confession time for {username} 🤭",
  "Secretly sliding this for {username} 🛷",
  "Your inbox is about to get sneaky for {username} 😼",
  "Mysterious digital whispers for {username} 🌀",
  "Ssshh… {username} won’t know who sent it 🤫",
  "Stealth delivery for {username} 🥷",
  "Ghost message en route for {username} 👻",
  "Anonymous surprise for {username} 😏",
  "A quiet note for {username} 🌬️",
  "Top-secret delivery for {username} 🕶️",
  "Message in stealth mode for {username} 🛡️",
  "Confidential vibes only for {username} 🤐",
  "You’ve got a ninja note for {username} 🥷",
  "Mystery mail just for {username} ✨",
  "Ssshh… secret delivery for {username} 🤫",
  "Sliding into {username}’s inbox quietly 🛷",
  "Psst… a ghostly whisper for {username} 👻",
  "Oops… sneaky note for {username} 😏",
  "Digital secret for {username} 🌐",
  "Message in disguise for {username} 🕵️‍♂️",
  "Anonymous alert for {username} 🚨",
  "Top-secret whisper for {username} 🕶️",
  "Shh… mystery message for {username} 🤐",
  "Your stealth note for {username} 🥷",
  "Sneaky delivery for {username} 😼",
  "Ghostly vibes for {username} 👻",
  "Sliding a secret note to {username} 🛷",
  "Confidential message for {username} 🕵️",
  "Oops… anonymous note for {username} 😏",
  "Secretly sent to {username} 🤫",
  "Mysterious delivery for {username} 🌀",
  "Top-secret alert for {username} 🚨",
  "Whispers just for {username} 🌬️",
  "Ssshh… hidden message for {username} 🤐",
  "You’ve got stealth vibes for {username} 🥷",
  "Ghost message for {username} 👻",
  "Anonymous vibes incoming for {username} ✨",
  "Psst… a secret note for {username} 🕵️",
  "Sliding this anonymously for {username} 😏",
  "Oops… mystery mail for {username} 👀",
  "Quietly delivered to {username} 🤫",
  "Your ninja note for {username} 🥷",
  "Top-secret delivery for {username} 🚀",
  "Ssshh… this one’s for {username} 🤐",
  "Confession just for {username} 🤭",
  "Sneaky whisper for {username} 😼",
  "Mysterious vibes for {username} 🌀",
  "Ghostly delivery for {username} 👻",
  "Anonymous surprise for {username} ✨",
  "Sliding stealthily for {username} 🛷",
  "Digital secret just for {username} 🌐",
  "Top-secret ninja note for {username} 🥷",
  "Oops… stealth message for {username} 😏",
  "Quiet vibes for {username} 🤫",
  "Your inbox just got sneaky for {username} 😼",
  "Secret alert for {username} 🚨",
  "Mystery note coming for {username} 👀",
  "Ssshh… ninja delivery for {username} 🥷",
  "Anonymous whisper for {username} 🌬️",
  "Sliding a ghostly message to {username} 👻",
  "Confidential vibes for {username} 🤐",
  "Oops… mystery delivery for {username} 😏",
  "Top-secret message for {username} 🕶️",
  "Shh… secret note for {username} 🤫",
  "Your stealthy vibes for {username} 🥷",
  "Ghost note incoming for {username} 👻",
  "Sneaky message for {username} 😼",
  "Sliding this to {username}… quietly 🛷",
  "Digital ninja vibes for {username} 🌐",
  "Mystery whisper just for {username} 🌀",
  "Anonymous alert incoming for {username} 🚨",
  "Ssshh… stealthy note for {username} 🤐",
  "Confession alert for {username} 🤭",
  "Oops… sneaky vibes for {username} 😏",
  "Sliding stealth delivery for {username} 🛷",
  "Top-secret whisper vibes for {username} 🕶️",
  "Ghostly vibes just for {username} 👻",
  "Your inbox is mysterious for {username} 🌬️",
  "Anonymous ninja note for {username} 🥷",
  "Ssshh… secret vibes for {username} 🤫",
];
