-- AlterTable
ALTER TABLE "user" ADD COLUMN     "dailyLimit" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "isDisabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lastResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "messagesToday" INTEGER NOT NULL DEFAULT 0;
